export const EXCEPTION_KEY = 'exception_key'
export const CONTROLLER_EXCEPTION_KEY = 'controller_exception_key'
export const INJECT_KEY = 'inject_key'
export const INJECTABLE_KEY = 'injectable_key'
export const PATH_KEY = 'path_key'
export const MIDDLEWARE_KEY = 'middleware_key'
export const POST_MIDDLEWARE_KEY = 'post_middleware_key'
export const CONTROLLER_MIDDLEWARE_KEY = 'controller_middleware_key'
export const POST_CONTROLLER_MIDDLEWARE_KEY = 'post_controller_middleware_key'

// http
export const METHOD_KEY = 'method_key'
export const REQUEST_KEY = 'request_key'
export const RESPONSE_KEY = 'response_key'
export const REQUEST_QUERY_KEY = 'request_query_key'
export const REQUEST_PARAM_KEY = 'request_param_key'
export const REQUEST_BODY_KEY = 'request_body_key'
